### ISSUE TITLE
create API alpha ver.

### ISSUE THREAD

**Issue by oshimaryo** [mozilla-japan/gitfab2#1192]
## Tasks
- [x] API Design
- [x] Authentication
- [x] Write Test
- [x] Implementation
- [x] Documentation

### links
- [x] [#350 REST API Versioning - Rails cast](http://railscasts.com/episodes/350-rest-api-versioning?view=asciicast)
- [ ]  [API on Rails](http://apionrails.icalialabs.com/book)
- [ ] [10 Design Tips for APIs](https://localize-software.phraseapp.com/posts/best-practice-10-design-tips-for-apis/)
- [ ] [Building a RESTful API in a Rails application](https://www.airpair.com/ruby-on-rails/posts/building-a-restful-api-in-a-rails-application)
- [x] [Best Practices for Designing a Pragmatic RESTful API | Vinay sahni](http://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api)
- [x] [Web API 設計のベストプラクティス集 "Web API Design - Crafting Interfaces that Developers Love"](http://d.hatena.ne.jp/cou929_la/20130121/1358776754)

#### Supporting RESTfull API 
* [Garage](https://github.com/cookpad/garage)
* [Grape](https://github.com/ruby-grape/grape)
* [Rails::API](https://github.com/rails-api/rails-api)

#### versioning
* [versionist](https://github.com/bploetz/versionist)

#### Authentication
* [Doorkeeper](https://github.com/doorkeeper-gem/doorkeeper)
* [DeviseTokenAuth](https://github.com/lynndylanhurley/devise_token_auth)
* [OmniAuth](https://github.com/intridea/omniauth)

**Comment by oshimaryo** [comment]
# 実装の方針

## OAuthの土管になる

#### 概要
* Fabble は OAuth Provider にはならない
* Fabbleにサービス登録用の画面/APIがあり、3rd Partyはそこで、consumer_key / consumer_secret が発行される
* この key/secret が書かれたクライアント(3rd Party)からしか通信できない
* 3rd Partyでユーザが登録ボタンを押すと、
 1. Fabbleに一旦アクセスするとリダイレクトされて
 1. GitHubの画面にOAuthに飛び、
 1. 認証されるとOAuth TokenがGitHubからFabbleに渡され、
 1. Fabble はそのOAuth Tokenをベースに、SecureRandomを使って独自のToken（Fabble Token）を生成し
 1. Fabble Tokenを3rd Partyに渡すとブラウザに保存される。
* Fabble APIを通して通信をする際には上記のFabble Tokenを渡し、認証する
* Fabble Token
* Fabble Tokenは一定の期間でexpireする
* Fabble Tokenがexpireした場合に通信されると、header/bodyにその旨書かれたjsonが返される


#### 必要な実装
* https化
* 

#### メリット

#### デメリット
* Fabbleの
* 通信のセキュリティを担保する必要がる
